fix: drop #[uniffi(default)] for now because uniffi-bindgen-react-native doesn't like it
I get this:
> Generating bindings and turbo module from lib file /Users/ryan/w/livekit/rust-sdks/target/debug/liblivekit_uniffi.dylib
> Error: finding components in '/Users/ryan/w/livekit/rust-sdks/target/debug/liblivekit_uniffi.dylib'
>
> Caused by:
>     0: extracting metadata for '_UNIFFI_META_LIVEKIT_UNIFFI_RECORD_TOKENOPTIONS'
>     1: field ttl of type Optional { inner_type: Duration } can't have a default value of type string